eureka:
  instance:
    prefer-ip-address: true
    ip-address: 9.98.12.25:31708
    hostname: ${spring.application.name}.default.svc.cluster.local
    instance-id: ${spring.application.name}.default.svc.cluster.local:${server.port}
    nonSecurePort: 80
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka/
