eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    prefer-ip-address: true
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
