eureka:
  instance:
    hostname: discovery-service.default.svc.cluster.local:8761
    nonSecurePort: 80
    metadataMap:
      instanceId: ${spring.application.name}.default.svc.cluster.local:${server.port}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka/
