eureka:
  instance:
    prefer-ip-address: true
    hostname: 9.98.12.25:31708
    instance-id: 9.98.12.25:31708
    nonSecurePort: 80
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 5
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-service.default.svc.cluster.local:8761/eureka/
