spring:
  profiles:
    active: development
---
spring:
  profiles: cloud
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://edge-service.default.svc.cluster.local:9999
    auth-service:
      path: /user/**
      url: http://9.98.12.25:31704/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://9.98.12.25:31704/uaa/user
    client:
      accessTokenUri: http://9.98.12.25:31704/uaa/oauth/token
      userAuthorizationUri: http://9.98.12.25:31704/uaa/oauth/authorize
      clientId: acmenew
      clientSecret: acmesecretnew
  ignored: /assets/**
server:
  session:
    cookie:
      name: APPSESSIONID123
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9999
    auth-service:
      path: /user/**
      url: http://localhost:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/uaa/user
    client:
      accessTokenUri: http://localhost:8181/uaa/oauth/token
      userAuthorizationUri: http://localhost:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://${DOCKER_IP:192.168.99.100}:9999
    auth-service:
      path: /user/**
      url: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/user
    client:
      accessTokenUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/token
      userAuthorizationUri: http://${DOCKER_IP:192.168.99.100}:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 8787
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
